version: 5
settings:
  hack: true
  config:
    disabled: false
  log:
    level: info
  commit:
    key:
      enabled: true
      required: true
      prompt:
        select:
          page: 5
          suggestion: false
          values:
            - key: feat
              text: Introducing new features
            - key: perf
              text: Improving user experience / usability / reliablity
            - key: fix
              text: Fixing a bug
            - key: chore
              text: Other changes unrelated to user/client
    scope:
      enabled: true
      required: false
      prompt:
        select:
          page: 5
          suggestion: false
          values:
            - key: ui
              text: User interface or frontend design
            - key: lib
              text: All data from lib directory
            - key: deps
              text: Dependencies
            - key: script
              text: Internal scripts
            - key: docs
              text: Documentation included only README and CHANGELOG
            - key: posts
              text: Posts in _posts/en and _posts/th directories

    title:
      enabled: true
      required: true
      prompt:
        input:
          max: 75
          multiline: false
    message:
      enabled: false
      required: false
      prompt:
        input:
          max: 200
          multiline: true
