style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/kamontat/blog
options:
  commits:
    filters:
      Type:
        - feat
        - perf
        - fix
  commit_groups:
    title_maps:
      feat: Features
      perf: Improvement
      fix: Bug Fixes
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
